### ISSUE TITLE
Updater la liste des commanditaires

### ISSUE THREAD

**Issue by ldionmarcil** [dciets/dciets.github.io#7]

**Comment by ldionmarcil** [comment]
* Trouver un sample logo pour ETTIC/Desjardins

**Comment by jerome-gingras** [comment]
Ils devraient pas aussi se trouver dans le footer aussi? (Ça semble être les diamants...)

**Comment by ldionmarcil** [comment]
Oui, c'est pour ça que le ticket est pas fermé. J'ai juste eu le temps de
faire celui-là hier, en mode priorité. C'est plus chiant que je pensais
trouver un logo et le dimensionner comme il faut.

2015-01-31 19:51 GMT-05:00 Jerome Gingras <notifications@github.com>:

**Comment by jerome-gingras** [comment]
J'ai updaté le footer puis j'ai réparé l'erreur de site web de Louis,
